archive/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from archive import views

urlpatterns = [
    
    path('', views.performances, name="performances"),

    path('<int:performance_id>', views.performance, name="performance"),

    path('new_performance/<int:replay_id>', views.new_performance, name="new_performance"),

    path('edit_performance/<int:performance_id>', views.edit_performance, name="edit_performance"),

    path('delete_performance/<int:performance_id>', views.delete_performance, name="delete_performance"),

    path('share/', views.new_public_video, name="share"),

]

uploads/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [

    path('', include('uploads.core.urls')),

    path('admin/', admin.site.urls),

    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),

    path('archive/', include(('archive.urls', 'archive'), namespace='archive')),

    path('users/', include(('users.urls', 'users'), namespace='users')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('auth/', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Defines URL patterns for users"""

from django.conf.urls import url
from django.contrib.auth.views import login
from django.urls import path, reverse
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    # logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # registration page
    url(r'^register/$', views.register, name='register'),

    path('edit_user/', views.edit_user, name='edit_user'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='users/change_password.html',), name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/reset_password.html', 
        success_url='/users/password_reset/done/'), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/reset_password_done.html'), name='password_reset_done'),
]

archive/models.py
from django.db import models
from uploads.core.models import Replay

class Performance(models.Model):
    note = models.CharField(max_length=255, blank=True)
    pilot = models.CharField(max_length=200, blank=True)
    team = models.CharField(max_length=200, blank=True)
    rally = models.CharField(max_length=200, blank=True)
    track = models.CharField(max_length=200, blank=False)
    stage_number = models.CharField(max_length=200, blank=True)
    car = models.CharField(max_length=200, blank=True)
    category = models.CharField(max_length=200, blank=True)
    time = models.CharField(max_length=200, blank=True)
    youtube_id = models.CharField(max_length=200, blank=False)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    featured = models.BooleanField(default=False)
    replay = models.OneToOneField(Replay, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return '{} - {}'.format(self.uploaded_at, self.track)

    class Meta:
        ordering = ('-featured', '-uploaded_at',)

archive/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from archive.models import Performance
from uploads.core.utils import parse_youtube_id, parse_car, parse_stage, parse_category, parse_rally

class PerformanceForm(forms.ModelForm):

    class Meta:
        abstract = True
        model = Performance
        fields = ('track', 'youtube_id', 'car', 'time', 'category', 'pilot', 'team', 'rally', 'stage_number', 'note', 'replay', 'featured')

        labels = {
            'track': _('Track Name'),
            'youtube_id': _('YouTube URL or ID'),
            'car': _('Car'),
            'time': _('Time'),
            'category': _('Category'),
            'pilot': _('Pilot'),
            'team': _('Team'),
            'rally': _('Rally'),
            'stage_number': _('Stage (SS)'),
            'note': _('Comments'),
            'gdpr_accept': _('I accept that these information collected will be used for the only purpose of creating videos inherent RealRally.')
        }

        help_texts = {
            'track': _('*Required'),
            'youtube_id': _('*Required'),
            'gdpr_accept': _('*Required')
        }

    def clean_youtube_id(self):
        data = self.cleaned_data['youtube_id']
        return parse_youtube_id(data)

class PublicPerformanceForm(PerformanceForm):
    gdpr_accept = forms.BooleanField(required=True, label=_('I accept that these information collected will be used for the only purpose of creating videos inherent RealRally.'))

    class Meta(PerformanceForm.Meta):
        fields = ('track', 'youtube_id', 'car', 'time', 'category', 'pilot', 'team', 'rally', 'stage_number', 'note', 'gdpr_accept')

    def clean_gdpr_accept(self):
        gdpr_accept = self.cleaned_data.get('gdpr_accept')
        if not gdpr_accept:
            self.add_error('gdpr_accept', _("Please accept the terms."))

        return gdpr_accept

def initial_from_replay(replay):
    return {
        'replay': replay,
        'pilot': replay.document.pilot_nickname,
        'note': replay.document.note,
        'stage_number': parse_stage(replay.replay.name),
        'car': parse_car(replay.replay.name),
        'category': parse_category(replay.replay.name),
        'rally': parse_rally(replay.replay.name),
    }

archive/views.py
import time
import sys
import dateutil.parser
from datetime import timedelta, date
from django.shortcuts import render
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from archive.models import Performance
from archive.forms import PerformanceForm, PublicPerformanceForm, initial_from_replay
from archive.performance import index, delete, search
from uploads.core.models import Replay
from uploads.core.utils import parse_date, parse_stage, parse_category, parse_car
from requests.exceptions import ConnectionError

def performances(request):
    start = time.time()
    data = request.GET
    page = data.get('page', 1)
    try:
        document_list, total, took = search(search=data.get('search'))
    except ConnectionError:
        document_list = Performance.objects.all()
        if data.get('search', '') != '':
            document_list = document_list.filter(
                Q(pilot__icontains=data.get('search')) | 
                Q(car__icontains=data.get('search')) |
                Q(rally__icontains=data.get('search')) |
                Q(team__icontains=data.get('search')) | 
                Q(track__icontains=data.get('search'))
            )
        total = document_list.count(); took = 0

    paginator = Paginator(document_list, 18, orphans=5) # Show 25 contacts per page
    documents = paginator.get_page(page)

    return render(request, 'archive/performances.html', {
        'performances': documents, 
        'total': total, 
        'form': data,
        'took': '{0:.3f}'.format(took or time.time() - start)
    })

@login_required
def new_performance(request, replay_id):
    if request.method != 'POST':
        replay = Replay.objects.get(id=replay_id)
        form = PerformanceForm(initial=initial_from_replay(replay))
    else:
        form = PerformanceForm(data=request.POST)
        if form.is_valid():
            performance = form.save()
            index(performance)
            return HttpResponseRedirect(reverse('archive:performances'))

    context = {'form': form, 'replay_id': replay_id}
    return render(request, 'archive/new_performance.html', context)

def new_public_video(request):
    if request.method != 'POST':
        form = PublicPerformanceForm()
    else:
        form = PublicPerformanceForm(data=request.POST)
        if form.is_valid():
            performance = form.save()
            index(performance)
            return HttpResponseRedirect(reverse('archive:performances'))

    context = {'form': form}
    return render(request, 'archive/new_public_video.html', context)

def performance(request, performance_id):
    performance = get_object_or_404(Performance, id=performance_id)

    context = {'performance': performance}
    return render(request, 'archive/performance.html', context)

@login_required
def edit_performance(request, performance_id):
    """Edit an existing secret."""
    performance = get_object_or_404(Performance, id=performance_id)

    if request.method != 'POST':
        form = PerformanceForm(instance=performance)
    else:
        form = PerformanceForm(instance=performance, data=request.POST)
        if form.is_valid():
            performance = form.save()
            index(performance)
            return HttpResponseRedirect(reverse('archive:performances'))

    context = {'performance': performance, 'form': form}
    return render(request, 'archive/edit_performance.html', context)

@login_required
def delete_performance(request, performance_id):
    performance = get_object_or_404(Performance, id=performance_id)

    if request.method == "POST":
        delete(performance)
        return HttpResponseRedirect(reverse('archive:performances'))
    
    context = {'performance': performance}
    return render(request, 'archive/delete_performance.html', context)

archive/templates/archive/delete_performance.html
{% extends "base.html" %}{% load i18n %}
{% load material_form %}

{% block content %}
<div class="row valign">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <div class="card">
      <form action="{% url 'archive:delete_performance' performance.id  %}" method='post' >
        {% csrf_token %}
        <div class="card-content">
          <div class="card-title grey-text text-darken-2">Delete the performance "{{ performance }}"?</div>
        </div>
        <div class="card-action">
          <div class="right-align">
            <a href="{% url 'archive:performance' performance.id  %}" class="btn btn-primary waves-effect" >Cancel</a>
            <button type="submit" name="_submit" class="waves-effect waves-red btn-flat grey-text text-darken-3">delete</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

archive/templates/archive/edit_performance.html
{% extends "base.html" %}{% load i18n %}
{% load material_form %}

{% block content %}
  {% if messages %}
  <div class="messages">
      {% for message in messages %}
      <div{% if message.tags %} class="{{ message.tags }} card-panel {% if message.level_tag == 'error' %}red{% else %}green{% endif %}"{% endif %}>{{ message }}</div>
      {% endfor %}
  </div>
  {% endif %}
  <form action="{% url 'archive:edit_performance' performance.id  %}" method='post' class="viewform">
    <div class="section">
      {% csrf_token  %}
      {% form form=form %}{% endform %}
    </div>
    <div class="section right-align">
      <a href="{% url 'archive:performances' %}" class="waves-effect btn-flat grey-text text-darken-3">cancel</a>
      <button type="submit" name="_submit" class="btn btn-primary waves-effect"><i class="material-icons left" >save</i> update</button>
    </div>
  </form>
{% endblock content %}

archive/templates/archive/new_performance.html
{% extends "base.html" %}{% load i18n %}
{% load material_form %}

{% block content %}
  {% if messages %}
  <div class="messages">
      {% for message in messages %}
      <div{% if message.tags %} class="{{ message.tags }} card-panel {% if message.level_tag == 'error' %}red{% else %}green{% endif %}"{% endif %}>{{ message }}</div>
      {% endfor %}
  </div>
  {% endif %}
  <form action="{% url 'archive:new_performance' replay_id %}" method='post' class="viewform">
    <div class="section">
      {% csrf_token  %}
      {% form form=form %}{% endform %}
    </div>
    <div class="section right-align">
      <a href="{% url 'home' %}" class="waves-effect btn-flat grey-text text-darken-3">{% trans "Cancel" %}</a>
      <button type="submit" name="_submit" class="btn btn-primary waves-effect"><i class="material-icons left" >save</i>{% trans "Add video" %}</button>
    </div>
  </form>

  <p><a href="{% url 'home' %}">{% trans "Return to home" %}</a></p>
{% endblock content %}

{% block content-script %}
{% endblock %}

archive/templates/archive/new_public_video.html
{% extends "base.html" %}{% load i18n %}
{% load material_form %}

{% block content %}
  {% if messages %}
  <div class="messages">
      {% for message in messages %}
      <div{% if message.tags %} class="{{ message.tags }} card-panel {% if message.level_tag == 'error' %}red{% else %}green{% endif %}"{% endif %}>{{ message }}</div>
      {% endfor %}
  </div>
  {% endif %}
  <h5>{% trans "Share Video" %}</h5>
  <form action="{% url 'archive:share' %}" method='post' class="viewform">
    <div class="section">
      {% csrf_token  %}
      {% form form=form %}{% endform %}
    </div>
    <div class="section right-align">
      <a href="{% url 'home' %}" class="waves-effect btn-flat grey-text text-darken-3">{% trans "Cancel" %}</a>
      <button type="submit" name="_submit" class="btn btn-primary waves-effect"><i class="material-icons left" >save</i>{% trans "Add video" %}</button>
    </div>
  </form>

  <p><a href="{% url 'home' %}">{% trans "Return to home" %}</a></p>
{% endblock content %}

{% block content-script %}
{% endblock %}

archive/templates/archive/performance.html
{% extends "base.html" %}{% load i18n %}
{% load material_form %}

archive/templates/archive/performances.html
{% extends "base.html" %}{% load i18n %}
{% load material_form %}

{% block content %}
<div class="section">
  <div class="row">
    <div class="col s12">
      <div class="row">
        {% csrf_token %}
        <form action="{% url 'archive:performances' %}" method="GET">      
          <div class="input-field col m10 s9">
            <input name="search" id="search" type="search" value="{{ form.search  }}" >
            <label for="search"><i class="material-icons">search</i></label>
          </div>
          <div class="input-field col m2 s3">
            <button class="btn-floating green" type="submit"><i class="material-icons left" >search</i></button>
          </div>
        </form>
      </div>
      <div class="row">
        <div class="col">
            <h6>{% blocktrans %}About {{ total }} results ({{ took }} seconds){% endblocktrans %}</h6>
        </div>
      </div>
      <div class="row">
        {% for obj in performances %}
        <div class="col xl4 l6 m6 s12">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <!-- <div class="video-container">
                      <iframe width="853" height="480" src="https://www.youtube.com/embed/{{obj.youtube_id}}" frameborder="0" allowfullscreen></iframe>
                    </div> -->
                    <a href="https://www.youtube.com/watch?v={{obj.youtube_id}}" target="_blank" ><img class="responsive-img" src="https://img.youtube.com/vi/{{obj.youtube_id}}/mqdefault.jpg"></a>
                </div>
                <div class="card-content">
                    <span class="card-title activator grey-text text-darken-4">{{obj.track}}<i class="material-icons right">more_vert</i></span>
                    <p><b>{% trans "Pilot" %}: </b>{{obj.pilot}}</p>
                    <p><b>{% trans "Car" %}: </b>{{obj.car}}</p>
                    <p><b>{% trans "Team" %}: </b>{{obj.team}}</p>
                </div>
                {% if user.is_authenticated %}
                <div class="card-action right-align">
                    <a href="{% url 'archive:delete_performance' obj.id %}" >Delete</a>
                    <a href="{% url 'archive:edit_performance' obj.id %}" class="btn">Edit</a>
                </div>
                {% endif %}
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">{{obj.track}}<i class="material-icons right">close</i></span>
                    <p><b>Rally: </b>{{obj.rally}}</p>
                    <p><b>{% trans "Car" %}: </b>{{obj.car}}</p>
                    <p><b>{% trans "Pilot" %}: </b>{{obj.pilot}}</p>
                    <p><b>{% trans "Team" %}: </b>{{obj.team}}</p>
                    <p><b>{% trans "Category" %}: </b>{{obj.category}}</p>
                    <p><b>{% trans "Time" %}: </b>{{obj.time}}</p>
                    <p><b>{% trans "Stage (SS)" %}: </b>{{obj.stage_number}}</p>
                    <p><b>{% trans "Note" %}: </b>{{obj.note}}</p>
                    <p><b>{% trans "Uploaded" %}: </b>{{obj.uploaded_at|date:'D, d N H:i e'}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
      </div>
      <div class="section">
        <ul class="pagination">
          {% if performances.has_previous %}
          <li><a href="?page={{ performances.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
          {% endif %}
          {% for l in performances.paginator.page_range %}
            {% if l <= performances.number|add:5 and l >= performances.number|add:-5 %}
              {% if performances.number == l %}
              <li class="active"><a href="#!">{{forloop.counter}}</a></li>
              {% else %}
              <li class="waves-effect"><a href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
              {% endif %}
            {% endif %}
          {% endfor %}
          {% if performances.has_next %}
          <li class="waves-effect"><a href="?page={{ performances.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
          {% endif %}

        </ul>
        <!-- <div class="pagination">
          <span class="step-links">
            {% if performances.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ performances.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
              Page {{ performances.number }} of {{ performances.paginator.num_pages }}.
            </span>
    
            {% if performances.has_next %}
              <a href="?page={{ performances.next_page_number }}">next</a>
              <a href="?page={{ performances.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
          </span>
        </div> -->
      </div>
   </div>
  </div>
</div>
<script>
$(document).ready(function(){
  $('.datepicker').datepicker({
    format: 'yyyy-mm-dd', 
    autoClose: true, 
    showClearBtn: true
  });
});
</script>
{% endblock content %}