uploads/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [

    path('', include('uploads.core.urls')),

    path('admin/', admin.site.urls),

    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),

    path('archive/', include(('archive.urls', 'archive'), namespace='archive')),

    path('users/', include(('users.urls', 'users'), namespace='users')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('auth/', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Defines URL patterns for users"""

from django.conf.urls import url
from django.contrib.auth.views import login
from django.urls import path, reverse
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    # logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # registration page
    url(r'^register/$', views.register, name='register'),

    path('edit_user/', views.edit_user, name='edit_user'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='users/change_password.html',), name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/reset_password.html', 
        success_url='/users/password_reset/done/'), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/reset_password_done.html'), name='password_reset_done'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomUserChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].required = False
        self.fields["password2"].required = False

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.debug import sensitive_variables

from .forms import CustomUserChangeForm, CustomUserCreationForm

def logout_view(request):
    """Log the user out"""
    logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # display blank registration form
        form = CustomUserCreationForm()
    else:
        # process completed form.
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # log the user in and then redirect to home page
            # authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            # login(request, authenticated_user)
            return HttpResponseRedirect(reverse('home'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

@login_required
def edit_user(request):
    user = User.objects.get(pk=request.user.pk)
    if request.method != 'POST':
        form = CustomUserChangeForm(instance=user)
    else:
        form = CustomUserChangeForm(instance=user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('home'))

    context = {'form': form}
    return render(request, 'users/edit_user.html', context)

users/templates/users/change_password.html
{% extends "base.html"  %}
{% load material_form %}

{% block content  %}
<div class="row valign change-form">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <div class="card">
      <form method="post" action="{% url 'users:password_change' %}" class="viewform">
        <div class="card-content">
          <span class="card-title grey-text text-darken-2">Password change</span>
          <div class="section">
          {% csrf_token  %}
          {% form form=form %}{% endform %}
          </div>
        </div>
        <div class="card-action">
          <div class="right-align">
            <button name="_submit" class="btn btn-primary btn-lg">change my password</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/edit_user.html
{% extends "base.html"  %}
{% load material_form %}

{% block content  %}
<div class="row valign change-form">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <div class="card">
      <form method="post" action="{% url 'users:edit_user' %}">
        <div class="card-content">
          <span class="card-title grey-text text-darken-2">User Information</span>
          <div class="section">
          {% csrf_token  %}
          {% form form=form %}{% endform %}
          </div>
        </div>
        <div class="card-action">
          <div class="right-align">
              <button type="submit" name="_submit" class="btn btn-primary waves-effect"><i class="material-icons left" >save</i> update</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content  %}

users/templates/users/login.html
{% extends "base.html"  %}{% load static %}
{% load material_form %}

{% block content  %}
<style>
.extra-auth-buttons .btn { margin: 5px; }
</style>
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/bootstrap-social.css' %}" rel="stylesheet" type="text/css" />
<div class="row valign change-form">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <div class="card">
      <form method="post" action="{% url 'users:login' %}" class="viewform">
        <div class="card-content">
          <span class="card-title grey-text text-darken-2">Sign in</span>
          <div class="section">
          {% csrf_token  %}
          {% form form=form %}{% endform %}
          </div>
          {% if form.errors %}
          <div class="section">
          <p>Your username and password didn't match. Please try again.</p>
          </div>
          {% endif  %}
          <input type="hidden" name="next" value="{{ next }}" />
          <div class="right-align">
            <a href="{% url 'users:password_reset' %}" >Forgot your password?</a>
          </div>
        </div>
        <div class="card-action">
          <div class="right-align">
            <button name="_submit" class="btn btn-primary">Log in</button>
          </div>
          <p class="flow-text center">or<br/>log in with the following provider</p>
          <div class="section">
            <p class="center"><a class="waves-effect waves-light btn btn-block btn-social btn-google" href="{% url 'social:begin' 'google-oauth2' %}"><span class="fa fa-google"></span> Google</a></p>
            <!--<p class="center"><a class="waves-effect waves-light btn btn-block btn-social btn-github " href="{% url 'social:begin' 'github' %}"><span class="fa fa-github"></span> GitHub</a></p>
            <p class="center"><a class="waves-effect waves-light btn btn-block grey darken-4 amber-text" href="{% url 'social:begin' 'kakao' %}">Kakao</a></p>-->
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content  %}

users/templates/users/register.html
{% extends "base.html"  %}
{% load material_form %}

{% block content  %}
<div class="row valign change-form">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <div class="card">
      <form method="post" action="{% url 'users:register' %}" class="viewform">
        <div class="card-content">
          <span class="card-title grey-text text-darken-2">Registration form</span>
          <div class="section">
          {% csrf_token  %}
          {% form form=form %}{% endform %}
          </div>
          <input type="hidden" name="next" value="{{ next }}" />
        </div>
        <div class="card-action">
          <div class="right-align">
            <button name="_submit" class="btn btn-primary btn-lg">register</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content  %}

users/templates/users/reset_password.html
{% extends "base.html"  %}
{% load material_form %}

{% block content  %}
<div class="row valign change-form">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <div class="card">
      <form method="post" action="{% url 'users:password_reset' %}" class="viewform">
        <div class="card-content">
          <span class="card-title grey-text text-darken-2">Reset password</span>
          <div class="section">
          {% csrf_token  %}
          {% form form=form %}{% endform %}
          </div>
        </div>
        <div class="card-action">
          <div class="right-align">
            <button name="_submit" class="btn btn-primary btn-lg">reset my password</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/users/reset_password_done.html
{% extends "base.html"  %}
{% load material_form %}

{% block content  %}
<div class="row valign change-form">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <div class="card">
      <form method="post" action="{% url 'users:password_reset' %}" class="viewform">
        <div class="card-content">
          <span class="card-title grey-text text-darken-2">Password reset sent</span>
          <p class="section">We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
          <p class="section">If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
        </div>
        <div class="card-action">
          <div class="right-align">
            <a href="{% url 'users:login' %}" class="btn btn-primary">log in</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}