archive/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from archive import views

urlpatterns = [
    
    path('', views.performances, name="performances"),

    path('<int:performance_id>', views.performance, name="performance"),

    path('new_performance/<int:replay_id>', views.new_performance, name="new_performance"),

    path('edit_performance/<int:performance_id>', views.edit_performance, name="edit_performance"),

    path('delete_performance/<int:performance_id>', views.delete_performance, name="delete_performance"),

    path('share/', views.new_public_video, name="share"),

]

uploads/core/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

from uploads.core import views

urlpatterns = [

    url(r'^$', views.home, name='home'),

    url(r'^uploads/form/$', views.ReplayUploadView.as_view(), name='model_form_upload'),
    
    url(r'^replays/', views.replays, name='replays'),

    url(r'^edit_replay/(?P<replay_id>\d+)/$', views.edit_replay, name='edit_replay'),

]

uploads/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [

    path('', include('uploads.core.urls')),

    path('admin/', admin.site.urls),

    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),

    path('archive/', include(('archive.urls', 'archive'), namespace='archive')),

    path('users/', include(('users.urls', 'users'), namespace='users')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('auth/', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Defines URL patterns for users"""

from django.conf.urls import url
from django.contrib.auth.views import login
from django.urls import path, reverse
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    # logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # registration page
    url(r'^register/$', views.register, name='register'),

    path('edit_user/', views.edit_user, name='edit_user'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='users/change_password.html',), name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/reset_password.html', 
        success_url='/users/password_reset/done/'), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/reset_password_done.html'), name='password_reset_done'),
]

uploads/core/models.py
from django.db import models
from time import gmtime, strftime
from .validators import validate_file_size, validate_replay_file

def date_directory_path():
    return strftime("%Y-%m-%d", gmtime())

def replay_directory_path(instance, filename):
    return '{0}/{1}/replays/{2}'.format(date_directory_path(), instance.document.pilot_nickname, filename)

def skin_directory_path(instance, filename):
    return '{0}/{1}/skins/{2}'.format(date_directory_path(), instance.pilot_nickname, filename)

class Document(models.Model):
    note = models.CharField(max_length=255, blank=True)
    skin = models.FileField(upload_to=skin_directory_path, blank=True, null=True, validators=[validate_file_size])
    pilot_name = models.CharField(max_length=200, blank=True)
    pilot_nickname = models.CharField(max_length=200, blank=False)
    copilot_name = models.CharField(max_length=200, blank=True)
    copilot_nickname = models.CharField(max_length=200, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    gdpr_accept = models.BooleanField(blank=False)

    def __str__(self):
        return '{} - {}'.format(self.uploaded_at, self.pilot_nickname)

    class Meta:
        ordering = ('-uploaded_at', 'pilot_name')

class Replay(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    replay = models.FileField(upload_to=replay_directory_path, blank=True, null=True, validators=[validate_file_size, validate_replay_file])
    edited = models.BooleanField(default=False)

    def save(self, document=None):
        if document:
            self.document = document
        return super().save()

    def __str__(self):
        return self.replay.name

uploads/core/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from uploads.core.models import Document, Replay
from material import Layout, Row

class DocumentForm(forms.ModelForm):
    note = forms.CharField(widget=forms.Textarea(attrs={'cols': 80}), required=False)
    replays = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=True, 
    help_text=_('You can upload several replay files, make sure you upload only the original files, no other files are permitted.'))
    #field_order = ['label', 'category', 'username', 'password', 'confirm_password', 'ip', 'url', 'config', 'notes', 'groups']

    layout = Layout(
        Row('pilot_nickname', 'pilot_name'),
        Row('copilot_nickname', 'copilot_name'),
        'note', 'replays', 'skin', 'gdpr_accept',
    )
    
    class Meta:
        model = Document
        fields = ('pilot_nickname', 'pilot_name', 'copilot_nickname', 'copilot_name', 'note', 'replays', 'skin', 'gdpr_accept')
        help_texts = {
            'pilot_nickname': _('*Required'),
            'pilot_name': _('This name might be included on videos and other resources online, make sure you read the terms.'),
            'copilot_name': _('This name might be included on videos and other resources online, make sure you read the terms.'),
            'skin': _('This is the skin of the car, please upload a compressed file with only the files you edited!')
        }
        labels = {
            'pilot_name': _('Driver Real Name'),
            'pilot_nickname': _('Driver Nickname'),
            'copilot_name': _('Co-driver Real Name'),
            'copilot_nickname': _('Co-driver Nickname'),
            'note': _('Comments'),
            'gdpr_accept': _('I accept that these information collected will be used for the only purpose of creating videos inherent RealRally.'),
        }

    def clean_gdpr_accept(self):
        gdpr_accept = self.cleaned_data.get('gdpr_accept')
        if not gdpr_accept:
            self.add_error('gdpr_accept', _("Please accept the terms."))

        return gdpr_accept

class ReplayForm(forms.ModelForm):
    edited = forms.BooleanField(required=False)

    class Meta:
        model = Replay
        fields = ('edited',)

uploads/core/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.forms.utils import ErrorList
from django.views import View
from django.db.models import Q
from django.utils.translation import gettext as _

from uploads.core.models import Document, Replay
from uploads.core.forms import DocumentForm, ReplayForm
from uploads.core import validators
from uploads.core.maker import Maker
from uploads.core.utils import parse_date

from archive.models import Performance

def home(request):
    #performances = Performance.objects.all().filter(featured=True)
    performances = Performance.objects.all()[:6]
    return render(request, 'core/home.html', {'performances': performances, 'video_url': settings.HOME_VIDEO_URL})

@login_required
def replays(request):
    documents = Document.objects.all()
    data = request.GET
    
    if data.get('search', '') != '':
        documents = documents.filter(
            Q(pilot_nickname__icontains=data.get('search')) | 
            Q(pilot_name__icontains=data.get('search')) |
            Q(note__icontains=data.get('search')) |
            Q(replay__replay__icontains=data.get('search'))
        )
    
    if not data.get('edited'):
        documents = documents.filter(replay__edited=False)
    
    start_date = parse_date(data.get('from_date'))
    end_date = parse_date(data.get('to_date'))
    if start_date:
        documents = documents.filter(uploaded_at__gte=start_date)
    if end_date:
        documents = documents.filter(uploaded_at__lte=end_date + timedelta(days=1))
    
    documents = documents.distinct()

    return render(request, 'core/replays.html', {'documents': documents, 'form': data})

class ReplayUploadView(View):
    def get(self, request):
        form = DocumentForm()
        return render(request, 'core/model_form_upload.html', {'form': form})
    
    def post(self, request):
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            document = form.save(commit=False)
            replays = []
            for uploadedFile in request.FILES.getlist('replays'):
                try:
                    replays.append(self.handle_uploaded_replay(uploadedFile, document))
                except ValidationError as e:
                    errors = form._errors.setdefault("replays", ErrorList())
                    errors.append(e.message)
                    messages.error(request, e.message)

            if form.is_valid():
                document.save()
                form.save_m2m()
                for replay in replays:
                    replay.save(document)
                messages.success(request, _('Thank you, we will create awesomeness with your contribution!'))
                send_notification()
                return redirect(reverse('model_form_upload'))

        return render(request, 'core/model_form_upload.html', {'form': form})

    def handle_uploaded_replay(self, replay, document):
        validators.validate_file_size(replay)
        validators.validate_replay_file(replay)
        replay = Replay(replay=replay)
        replay.document = document
        return replay

@login_required
def edit_replay(request, replay_id):
    replay = get_object_or_404(Replay, id=replay_id)
    form = ReplayForm(instance=replay, data=request.POST)
    if form.is_valid():
        replay = form.save()
    return HttpResponse('')

def send_notification():
    maker = Maker()
    maker.send_async('rrwebtv_new_replay')

uploads/core/templates/core/home.html
{% extends "base.html" %}{% load static %}{% load i18n %}

{% block content %}
<div class="row">
  <div class="col s12 m10 offset-m1 l10 offset-l1">
    <div class="section">
      {% csrf_token %}
      <form action="{% url 'archive:performances' %}" method="GET">
        <div class="row">
          <div class="input-field col m10 s9">
            <input name="search" id="search" type="search" value="{{ form.search  }}" >
            <label for="search"><i class="material-icons">search</i></label>
          </div>
          <div class="input-field col m2 s3">
            <button class="btn-floating green" type="submit"><i class="material-icons left" >search</i></button>
          </div>
        </div>
      </form>
    </div>
    <div class="section">
      <h4>RealRally WebTV - Media Sharing</h4>
      <p>{% trans "home_message" %}</p>
    </div>
    <div class="section center-align" >
      <a href="{% url 'model_form_upload' %}" class="btn-floating btn-large red" title="{% trans "Upload Replay" %}"><i class="material-icons">cloud_upload</i></a>
      <a href="{% url 'archive:share' %}" class="btn-floating btn-large blue" title="{% trans "Share Video" %}"><i class="material-icons">share</i></a>
    </div>
    <div class="section">
      <div class="row">
      {% for obj in performances %}
      <div class="col l6 m12 s12">
        <div class="card">
          <div class="card-image">
            <!-- <div class="video-container">
              <iframe width="853" height="480" src="https://www.youtube.com/embed/{{obj.youtube_id}}" frameborder="0" allowfullscreen></iframe>
            </div> -->
            <a href="https://www.youtube.com/watch?v={{obj.youtube_id}}" target="_blank" ><img src="https://img.youtube.com/vi/{{obj.youtube_id}}/mqdefault.jpg"></a>
            <span class="card-title">{{obj.track}}</span>
          </div>
          <div class="card-content">
            <p><b>{% trans "Pilot" %}: </b>{{obj.pilot}}</p>
            <p><b>{% trans "Car" %}: </b>{{obj.car}}</p>
            <p><b>{% trans "Team" %}: </b>{{obj.team}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    </div>
  </div>
</div>
{% endblock content %}

uploads/core/templates/core/model_form_upload.html
{% extends "base.html" %}{% load i18n %}
{% load material_form %}

{% block content %}
  {% if messages %}
  <div class="messages">
      {% for message in messages %}
      <div{% if message.tags %} class="{{ message.tags }} card-panel {% if message.level_tag == 'error' %}red{% else %}green{% endif %}"{% endif %}>{{ message }}</div>
      {% endfor %}
  </div>
  {% endif %}
  <h5>{% trans "Upload Replay" %}</h5>
  <p>{% trans "upload_message" %}</p>
  <form method="post" enctype="multipart/form-data">
    <div class="section">
    {% csrf_token %}
    {% form form=form layout=form.layout %}
      {% part form.pilot_nickname prefix %}<i class="material-icons prefix">airline_seat_recline_extra</i>{% endpart %}
      {% part form.copilot_nickname prefix %}<i class="material-icons prefix">record_voice_over</i>{% endpart %}
      {% part form.note prefix %}<i class="material-icons prefix">event_note</i>{% endpart %}
    {% endform %}
    </div>
    <div class="section right-align">
        <a href="{% url 'home' %}" class="waves-effect btn-flat grey-text text-darken-3">{% trans "Cancel" %}</a>
      <button type="submit" name="_submit" class="btn btn-primary waves-effect"><i class="material-icons left" >save</i>{% trans "Upload Replay" %}</button>
    </div>
  </form>

  <p><a href="{% url 'home' %}">{% trans "Return to home" %}</a></p>
{% endblock content %}

uploads/core/templates/core/replays.html
{% extends "base.html" %}

{% block content %}
<div class="section">
  <div class="row">
    <div class="col s12 m12 xl12">
      {% csrf_token %}
      <form action="{% url 'replays' %}" method="GET">
        <div class="row">
          <div class="input-field col s12">
            <input name="search" id="search" type="search" value="{{ form.search  }}" >
            <label for="search"><i class="material-icons">search</i></label>
          </div>
          <div class="input-field col s4">
            <i class="material-icons prefix">date_range</i>
            <input name="from_date" type="text" class="datepicker" value="{{ form.from_date }}">
            <label for="from_date">From</label>
          </div>
          <div class="input-field col s4">
            <input name="to_date" type="text" class="datepicker" value="{{ form.to_date }}">
            <label for="to_date">To</label>
          </div>
          <div class="input-field col s2">
            <label>
              <input type="checkbox" name="edited" {% if form.edited %}checked{% endif %} />
              <span>Edited</span>
            </label>
          </div>
          <div class="input-field col s2">
            <button class="btn" type="submit">Search</button>
          </div>
        </div>
      </form>
      <ul id="projects-collection" class="collection z-depth-1">
        {% for obj in documents %}
        <li class="collection-item">
          <div class="row collections-content">
            <div class="col s8"><h5 class="flow-text">Uploaded on {{ obj.uploaded_at }}</h5></div>
            <div class="col s4">
              <div class="secondary-content">{% if obj.gdpr_accept %}<span class="chip green white-text">GDPR</span>{% endif %}</div>
            </div>
            <div class="col s12">
              <span class="flow-text">{{ obj.pilot_nickname }} - {{ obj.pilot_name }}</span>
            </div>
            {% if obj.note %}
            <div class="col s12">
                <blockquote class="">{{obj.note}}</blockquote>
            </div>
            {% endif %}
            <div class="col s12">
              {% for replay in obj.replay_set.all %}
              <p class="collection-item">
                <span class="badge">
                  <label>
                    <input type="checkbox" {% if replay.edited %}checked{% endif %} class="edited" data-id="{{ replay.id }}"/>
                    <span>Edited</span>
                  </label>
                </span>
                <span class="badge">REPLAY</span>
                {% if not replay.performance %}
                <span class="badge">
                  <a href="{% url 'archive:new_performance' replay.id %}" >Archive</a>
                </span>
                {% endif %}
                {% if replay.performance %}
                <span class="badge">
                  <a href="{% url 'archive:edit_performance' replay.performance.id %}" >Edit video</a>
                </span>
                {% endif %}
                <a href="{{ replay.replay.url }}" class="" >{{ replay.replay.name|truncatechars:75 }}</a></p>
              {% endfor %}
              {% if obj.skin %}
              <a href="{{ obj.skin.url }}" class="collection-item" ><span class="badge">SKIN</span>{{ obj.skin.name|truncatechars:75 }}</a>
              {% endif %}
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
   </div>
  </div>
</div>
<script>
$(document).ready(function(){
  $('.datepicker').datepicker({
    format: 'yyyy-mm-dd', 
    autoClose: true, 
    showClearBtn: true
  });

  $('input.edited').change(function(){
    let data = new FormData();
    let replay_id = $(this).data('id');
    data.append('edited', $(this).is(':checked'));
    // add form input from hidden input elsewhere on the page
    data.append('csrfmiddlewaretoken', $('input[name="csrfmiddlewaretoken"]').attr('value'));
    fetch(`/edit_replay/${replay_id}/`, {
        method: 'POST',
        body: data,
        credentials: 'same-origin',
    });
  });
});
</script>
{% endblock content %}

uploads/core/templates/core/simple_upload.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}