archive/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from archive import views

urlpatterns = [
    
    path('', views.performances, name="performances"),

    path('<int:performance_id>', views.performance, name="performance"),

    path('new_performance/<int:replay_id>', views.new_performance, name="new_performance"),

    path('edit_performance/<int:performance_id>', views.edit_performance, name="edit_performance"),

    path('delete_performance/<int:performance_id>', views.delete_performance, name="delete_performance"),

    path('share/', views.new_public_video, name="share"),

]

uploads/core/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

from uploads.core import views

urlpatterns = [

    url(r'^$', views.home, name='home'),

    url(r'^uploads/form/$', views.ReplayUploadView.as_view(), name='model_form_upload'),
    
    url(r'^replays/', views.replays, name='replays'),

    url(r'^edit_replay/(?P<replay_id>\d+)/$', views.edit_replay, name='edit_replay'),

]

uploads/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [

    path('', include('uploads.core.urls')),

    path('admin/', admin.site.urls),

    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),

    path('archive/', include(('archive.urls', 'archive'), namespace='archive')),

    path('users/', include(('users.urls', 'users'), namespace='users')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('auth/', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Defines URL patterns for users"""

from django.conf.urls import url
from django.contrib.auth.views import login
from django.urls import path, reverse
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # login page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    # logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # registration page
    url(r'^register/$', views.register, name='register'),

    path('edit_user/', views.edit_user, name='edit_user'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='users/change_password.html',), name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/reset_password.html', 
        success_url='/users/password_reset/done/'), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/reset_password_done.html'), name='password_reset_done'),
]

uploads/core/models.py
from django.db import models
from time import gmtime, strftime
from .validators import validate_file_size, validate_replay_file

def date_directory_path():
    return strftime("%Y-%m-%d", gmtime())

def replay_directory_path(instance, filename):
    return '{0}/{1}/replays/{2}'.format(date_directory_path(), instance.document.pilot_nickname, filename)

def skin_directory_path(instance, filename):
    return '{0}/{1}/skins/{2}'.format(date_directory_path(), instance.pilot_nickname, filename)

class Document(models.Model):
    note = models.CharField(max_length=255, blank=True)
    skin = models.FileField(upload_to=skin_directory_path, blank=True, null=True, validators=[validate_file_size])
    pilot_name = models.CharField(max_length=200, blank=True)
    pilot_nickname = models.CharField(max_length=200, blank=False)
    copilot_name = models.CharField(max_length=200, blank=True)
    copilot_nickname = models.CharField(max_length=200, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    gdpr_accept = models.BooleanField(blank=False)

    def __str__(self):
        return '{} - {}'.format(self.uploaded_at, self.pilot_nickname)

    class Meta:
        ordering = ('-uploaded_at', 'pilot_name')

class Replay(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    replay = models.FileField(upload_to=replay_directory_path, blank=True, null=True, validators=[validate_file_size, validate_replay_file])
    edited = models.BooleanField(default=False)

    def save(self, document=None):
        if document:
            self.document = document
        return super().save()

    def __str__(self):
        return self.replay.name

uploads/core/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from uploads.core.models import Document, Replay
from material import Layout, Row

class DocumentForm(forms.ModelForm):
    note = forms.CharField(widget=forms.Textarea(attrs={'cols': 80}), required=False)
    replays = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=True, 
    help_text=_('You can upload several replay files, make sure you upload only the original files, no other files are permitted.'))
    #field_order = ['label', 'category', 'username', 'password', 'confirm_password', 'ip', 'url', 'config', 'notes', 'groups']

    layout = Layout(
        Row('pilot_nickname', 'pilot_name'),
        Row('copilot_nickname', 'copilot_name'),
        'note', 'replays', 'skin', 'gdpr_accept',
    )
    
    class Meta:
        model = Document
        fields = ('pilot_nickname', 'pilot_name', 'copilot_nickname', 'copilot_name', 'note', 'replays', 'skin', 'gdpr_accept')
        help_texts = {
            'pilot_nickname': _('*Required'),
            'pilot_name': _('This name might be included on videos and other resources online, make sure you read the terms.'),
            'copilot_name': _('This name might be included on videos and other resources online, make sure you read the terms.'),
            'skin': _('This is the skin of the car, please upload a compressed file with only the files you edited!')
        }
        labels = {
            'pilot_name': _('Driver Real Name'),
            'pilot_nickname': _('Driver Nickname'),
            'copilot_name': _('Co-driver Real Name'),
            'copilot_nickname': _('Co-driver Nickname'),
            'note': _('Comments'),
            'gdpr_accept': _('I accept that these information collected will be used for the only purpose of creating videos inherent RealRally.'),
        }

    def clean_gdpr_accept(self):
        gdpr_accept = self.cleaned_data.get('gdpr_accept')
        if not gdpr_accept:
            self.add_error('gdpr_accept', _("Please accept the terms."))

        return gdpr_accept

class ReplayForm(forms.ModelForm):
    edited = forms.BooleanField(required=False)

    class Meta:
        model = Replay
        fields = ('edited',)

uploads/core/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.forms.utils import ErrorList
from django.views import View
from django.db.models import Q
from django.utils.translation import gettext as _

from uploads.core.models import Document, Replay
from uploads.core.forms import DocumentForm, ReplayForm
from uploads.core import validators
from uploads.core.maker import Maker
from uploads.core.utils import parse_date

from archive.models import Performance

def home(request):
    #performances = Performance.objects.all().filter(featured=True)
    performances = Performance.objects.all()[:6]
    return render(request, 'core/home.html', {'performances': performances, 'video_url': settings.HOME_VIDEO_URL})

@login_required
def replays(request):
    documents = Document.objects.all()
    data = request.GET
    
    if data.get('search', '') != '':
        documents = documents.filter(
            Q(pilot_nickname__icontains=data.get('search')) | 
            Q(pilot_name__icontains=data.get('search')) |
            Q(note__icontains=data.get('search')) |
            Q(replay__replay__icontains=data.get('search'))
        )
    
    if not data.get('edited'):
        documents = documents.filter(replay__edited=False)
    
    start_date = parse_date(data.get('from_date'))
    end_date = parse_date(data.get('to_date'))
    if start_date:
        documents = documents.filter(uploaded_at__gte=start_date)
    if end_date:
        documents = documents.filter(uploaded_at__lte=end_date + timedelta(days=1))
    
    documents = documents.distinct()

    return render(request, 'core/replays.html', {'documents': documents, 'form': data})

class ReplayUploadView(View):
    def get(self, request):
        form = DocumentForm()
        return render(request, 'core/model_form_upload.html', {'form': form})
    
    def post(self, request):
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            document = form.save(commit=False)
            replays = []
            for uploadedFile in request.FILES.getlist('replays'):
                try:
                    replays.append(self.handle_uploaded_replay(uploadedFile, document))
                except ValidationError as e:
                    errors = form._errors.setdefault("replays", ErrorList())
                    errors.append(e.message)
                    messages.error(request, e.message)

            if form.is_valid():
                document.save()
                form.save_m2m()
                for replay in replays:
                    replay.save(document)
                messages.success(request, _('Thank you, we will create awesomeness with your contribution!'))
                send_notification()
                return redirect(reverse('model_form_upload'))

        return render(request, 'core/model_form_upload.html', {'form': form})

    def handle_uploaded_replay(self, replay, document):
        validators.validate_file_size(replay)
        validators.validate_replay_file(replay)
        replay = Replay(replay=replay)
        replay.document = document
        return replay

@login_required
def edit_replay(request, replay_id):
    replay = get_object_or_404(Replay, id=replay_id)
    form = ReplayForm(instance=replay, data=request.POST)
    if form.is_valid():
        replay = form.save()
    return HttpResponse('')

def send_notification():
    maker = Maker()
    maker.send_async('rrwebtv_new_replay')

uploads/templates/base.html
<!DOCTYPE html>{% load static %}{% load i18n %}
<html>
  <head>
    <title>{% block title %}RealRally - WebTV - Media Sharing{% endblock %}</title>
    {% block head_favicon %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static '/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static '/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    {% endblock head_favicon %}
    {% block head_meta_charset %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {% endblock head_meta_charset %}
    {% block head_meta_contentlanguage %}
    <meta http-equiv="Content-Language" value="en-US" />
    {% endblock head_meta_contentlanguage %}
    {% block head_meta_viewport %}
    <meta name="viewport" content="width=device-width, initial-scale=0.8" />
    {% endblock head_meta_viewport %}

    {% include 'material/includes/material_css.html' %}
    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}

    <style>
      nav .brand-logo{margin-left:10px;}
      nav .brand-logo img {height: 42px; margin: 9px 0;}
      nav .extra-content{margin-left:150px;height: 100%;}
      body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }
      main {
        flex: 1 0 auto;
      }
      input[type=search] {
        -webkit-appearance: none;
      }
      @media only screen and (max-width: 992px) {
        nav .extra-content{margin-left:60px;}
        nav .brand-logo {
          left: 26%;
          transform: translateX(-16%);
        }
      }
    </style>
  </head>
  <body>
    <main>
    <div class="navbar-fixed">
      <nav class="" role="navigation">
        <div class="nav-wrapper"><a id="logo-container" href="/" class="brand-logo"><img src="{% static 'img/rrwebtv-logo.png' %}" alt="RealRally WebTV Logo" ></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'archive:performances' %}" ><i class="material-icons left">movie</i>{% trans "Videos" %}</a></li>
            <li><a href="https://rrgallery.emawind.com"><i class="material-icons left">photo_library</i>{% trans "Photos" %}</a></li>
            <li><a href="{% url 'archive:share' %}" ><i class="material-icons left">share</i>{% trans "Share Video" %}</a></li>
            <li><a href="{% url 'model_form_upload' %}" ><i class="material-icons left">cloud_upload</i>{% trans "Upload Replay" %}</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'replays' %}">Replays</a></li>
            {% if perms.auth.add_user %}
            <li><a href="{% url 'users:register' %}">Register</a></li>
            {% endif %}
            <li><a href="{% url 'users:logout' %}">Log out</a></li>
            {% else %}
            <li><a href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
          <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>
      </nav>
    </div>
    <ul id="nav-mobile" class="sidenav">
      <li><a href="{% url 'home' %}" ><i class="material-icons left">home</i>Home</a></li>
      <li><a href="{% url 'archive:performances' %}" ><i class="material-icons left">movie</i>{% trans "Videos" %}</a></li>
      <li><a href="https://rrgallery.emawind.com"><i class="material-icons left">photo_library</i>{% trans "Photos" %}</a></li>
      <li><a href="{% url 'archive:share' %}" ><i class="material-icons left">share</i>{% trans "Share Video" %}</a></li>
      <li><a href="{% url 'model_form_upload' %}"><i class="material-icons left">cloud_upload</i>{% trans "Upload Replay" %}</a></li>
      {% if user.is_authenticated %}
      <li><a href="{% url 'replays' %}">Replays</a></li>
      {% if perms.auth.add_user %}
      <li><a href="{% url 'users:register' %}">Register</a></li>
      {% endif %}
      <li><a href="{% url 'users:logout' %}">Log out</a></li>
      {% else %}
      <li><a href="{% url 'users:login' %}">Log in</a></li>
      {% endif %}
    </ul>
    <div class="container">
      {% block content %}{% endblock content %}
      {% block content-script %}{% endblock content-script %}
    </div>
    </main>
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l12 s12">
            <p class="light">{% trans "terms_message" %}</p>
          </div>
          <div class="col l3 s6">
            <div class="card transparent">
              <div class="card-content">
                <a href="http://realrally.com/"><img class="responsive-img" src="{% static 'img/realrally-logo2.png' %}" ></a>
              </div>
            </div>
          </div>
          <div class="col l3 s6">
            <div class="card transparent">
              <div class="card-content">
                <a href="https://www.emawind.com"><img class="responsive-img" src="{% static 'img/discofilm-logo2.png' %}" ></a>
              </div>
            </div>
          </div>
          <div class="col l3 s6">
            <div class="card transparent">
              <div class="card-content">
                <a href="http://www.etabetarace.it"><img class="responsive-img" src="{% static 'img/logo_etabetarace.png' %}" ></a>
              </div>
            </div>
          </div>
          <div class="col l3 s6">
            <div class="card transparent">
              <div class="card-content">
                <a href="https://www.facebook.com/Tuttorealrally"><img class="responsive-img" src="{% static 'img/TUTTOREALRALLY.png' %}" ></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container light">
        © 2019 Emanuele Disco All Rights Reserved
        </div>
      </div>
    </footer>

    {% block sidenav_javascript %}
    <script>
    $(document).ready(function(){
      $('.sidenav').sidenav();
    });
    </script>
    {% endblock sidenav_javascript %}
  </body>
</html>